kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-admin-web
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: FILADAPTER_URL
      value: https://pensjon-opptjening-filadapter.dev-fss-pub.nais.io
    - name: FILADAPTER_API_ID
      value: dev-fss.pensjonopptjening.pensjon-opptjening-filadapter
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe

  secureLogs:
    enabled: true
  ingresses:
    - https://pensjon-opptjening-admin-web.intern.dev.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pensjon-opptjening-filadapter.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 120
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 120
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
