kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-admin-web
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: FILADAPTER_URL
      value: https://pensjon-opptjening-filadapter.prod-fss-pub.nais.io
    - name: POPP_URL
      value: https://pensjon-popp.prod-fss-pub.nais.io/popp/api

  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "abd710c7-b01d-48e6-98b9-83ff615edf26" #AAD pensjonopptjening
  ingresses:
    - https://pensjon-opptjening-admin-web.intern.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pensjon-opptjening-filadapter.prod-fss-pub.nais.io
        - host: pensjon-popp.prod-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 120
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 120
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
